project:
  type: website

website:
  title: "Avni Dubey - Data Storytelling"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
    right:
      - href: about.qmd
        text: "About Me"
      - icon: github
        href: "https://github.com/assignment-3-v2-creating-a-blog-adub0006"

format:
  html:
    theme: cosmo
    css: styles.css



