{
  "hash": "e966105459a069a425a174b65ff50223",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Which Form of Transport Has the Smallest Carbon Footprint?\"\nauthor: \"Avni Dubey\"\ndate: \"2024-10-04\"\ncategories: [news]\n    \n---\n\n\nWelcome to my Blog Post\n\n\n![](thumbnail.jpg)\n\n\n## Introduction: How Much Do Your Travel Choices Affect the Environment?\n\nAs the world tackles the climate crisis, it’s becoming clear that how we choose to travel can make a big impact on the planet. From flying across countries to driving to work, the emissions we produce are contributing to global carbon dioxide (CO2) levels, which in turn accelerate climate change. \n\nBut did you know that some forms of transport are far more eco-friendly than others? This blog post will explore which modes of transport have the smallest carbon footprint, using data from the **UK Government’s Department for Energy Security and Net Zero (2022)**, and provide some insights into how you can reduce your travel-related emissions.\n\n## The Problem: Carbon Emissions from Transport\n\nTransport accounts for roughly one-quarter of global CO2 emissions. In developed countries with extensive infrastructure, it represents a significant portion of an individual’s carbon footprint. The key question many environmentally conscious travelers are asking is: **Which form of transport is the least harmful to the planet, and how can we make smarter choices?**\n\n---\n\n## Data Overview: What Do the Numbers Tell Us?\n\nWe analyzed data provided by the **Our World Data (UK Government’s Department for Energy Security and Net Zero (2022))**, which compared carbon emissions (in grams of CO2 per kilometre) for various transport modes. The following key variables were considered:\n\n- **gCO2eq/km**: Grams of CO2-equivalent emitted per kilometre traveled, considering all greenhouse gases.\n\n- **Transport mode**: The specific type of transport, including domestic flights, diesel cars, electric vehicles, trains, and buses etc.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table 1: Transport emissions per kilometer travelled by different transport modes.\n\n|Transport Mode         | Year| Emissions (gCO2/km)|\n|:----------------------|----:|-------------------:|\n|Bus (average)          | 2022|               96.50|\n|Bus (local London)     | 2022|               79.36|\n|Coach (bus)            | 2022|               27.33|\n|Diesel car             | 2022|              170.82|\n|Domestic flight        | 2022|              245.87|\n|Electric car           | 2022|               47.09|\n|Eurostar (to Paris)    | 2022|                4.46|\n|Ferry (foot passenger) | 2022|               18.74|\n|London Underground     | 2022|               27.81|\n|Long-haul flight       | 2022|              147.87|\n|Motorbike              | 2022|              113.55|\n|National rail          | 2022|               35.49|\n|Petrol car             | 2022|              170.48|\n|Plug-in hybrid         | 2022|               68.40|\n|Short-haul flight      | 2022|              151.02|\n|Tram                   | 2022|               28.61|\n\n\n:::\n:::\n\n\n\nAs shown in @table-transport-emissions , domestic flights have the highest emissions per kilometre, while public transport options like the Eurostar and London Underground produce significantly lower emissions.\n\n\n### Data Cleaning Steps:\nThe dataset was cleaned to remove irrelevant or outdated transport modes and focused only on modern, frequently used forms of transport. Missing data was handled by interpolation where needed, and values were standardized to gCO2/km to enable easy comparison.\n\n---\n\n## Analysis: The Clear Winners and Losers\n\nFrom the table above, it’s clear that **domestic flights** are the biggest offenders in terms of carbon emissions, producing a staggering 245.9 gCO2 per kilometre traveled. Diesel and petrol cars follow closely, with each emitting around 170 gCO2 per kilometre.\n\nOn the other end of the spectrum, **trains** emerge as the most environmentally friendly option. The Eurostar train, for example, emits just 4.5 gCO2/km, making it by far the most eco-conscious choice for long-distance travel.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n### What Does This Mean for the Average Traveler?\n\nIf you want to minimize your carbon footprint, switching from car travel to public transport (trains, buses) or even electric vehicles will make a significant difference .@fig-transport above visualizes these differences, showing the drastic reductions in emissions when using greener forms of transport.\n\n---\n\n## Conclusion: Reducing Your Travel Emissions\n\nThe data is clear: if you’re looking to reduce your carbon emissions, **trains**, **public transport**, and **electric vehicles** are the way to go. Walking and cycling for shorter trips are, of course, the best options when feasible, emitting no CO2 at all.\n\nFor long-distance travel, **trains like the Eurostar** are by far the most eco-friendly option. If we want to contribute to the global effort to reduce emissions, making small changes in our daily travel choices can add up to a big difference over time.\n\n---\n\n## Academic Citation\n\n*Which form of transport has the smallest carbon footprint? How can individuals reduce their emissions from transport?*Ritchie, H. (2023, August 30) Our World in Data. Retrieved from [https://ourworldindata.org/travel-carbon-footprint](https://ourworldindata.org/travel-carbon-footprint)\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}